### PR TITLE
Add trajectory field to Sella object

### LINKED ISSUE #22: The `trajectory` class variable is not accessible when using `Sella`
Sella right now is not storing the `trajectory` class variable like the other ASE optimizers.

Here is an example, using the `master` branch of ASE:

```python
from ase.build import bulk
from ase.calculators.emt import EMT
from ase.optimize import BFGS
from sella.optimize import Sella

atoms = bulk("Cu") * (2, 1, 1)
atoms.calc = EMT()
dyn = BFGS(atoms,trajectory="test.traj")
dyn.run()
assert dyn.trajectory is not None # <---- this passes (note: using the `master` branch of ASE!)

atoms = bulk("Cu") * (2, 1, 1)
atoms.calc = EMT()
dyn = Sella(atoms,trajectory="test.traj")
dyn.run()
assert dyn.trajectory is not None # <---- this fails
```

Running the above snippet will yield an assertion error for Sella but not for BFGS. For those developing packages around Sella, it would be very convenient to be able to access the same properties as the other optimizers. Tagging @samblau.

### PR DESCRIPTION
**Pull request by ehermes**
Resolves #22

### CODE REVIEW

**Comment by arosen93** [comment]
Thank you!!!

**Comment by arosen93** [comment]
@ehermes: Doesn't seem like this resolves it.

I did `pip install https://github.com/zadorlab/sella.git@sella_trajectory` and reran the codeblock in my issue. Still errors out.

**Comment by ehermes** [comment]
> @ehermes: Doesn't seem like this resolves it.
> 
> I did `pip install git+https://github.com/zadorlab/sella.git@sella_trajectory` and reran the codeblock in my issue. Still errors out. I think because the `Optimizer` base class is being instantiated with `None` for the trajectory regardless.

Based on our discussion in #22, can you verify whether this is still the case?

**Comment by arosen93** [comment]
@ehermes: I still had it return `None` but maybe I need to try in a fresh env. Either way, I'm considering this essentially solved via smarter means... :)

**Comment by ehermes** [comment]
I'm just going to merge this anyway, as I see no reason not to.

**Pull request merged**
